<?php

declare(strict_types=1);

namespace BVP\Scraper\Tests\Scrapers;

use Carbon\CarbonImmutable as Carbon;

/**
 * @psalm-import-type RaceArguments from \BVP\Scraper\Tests\ScraperPsalmType
 * @psalm-import-type RaceExpected from \BVP\Scraper\Tests\ScraperPsalmType
 *
 * @author shimomo
 */
final class PreviewScraperDataProvider
{
    /**
     * @psalm-return non-empty-list<
     *     array{
     *         arguments: RaceArguments,
     *         expected: RaceExpected,
     *     }
     * >
     *
     * @return array
     */
    public static function scrapeProvider(): array
    {
        return [
            [
                'arguments' => [Carbon::parse('2017-03-31'), 24, 1],
                'expected' => [
                    'date' => '2017-03-31',
                    'stadium_number' => 24,
                    'race_number' => 1,
                    'weather_as_of_source' => '18:04現在',
                    'weather_as_of_race_number' => null,
                    'weather_as_of_time' => '18:04',
                    'wind_speed_source' => '7m',
                    'wind_speed' => 7,
                    'wind_direction_number_source' => '南西',
                    'wind_direction_number' => 11,
                    'wave_height_source' => '6cm',
                    'wave_height' => 6,
                    'weather_number_source' => '曇り',
                    'weather_number' => 2,
                    'air_temperature_source' => '13.0℃',
                    'air_temperature' => 13.0,
                    'water_temperature_source' => '14.0℃',
                    'water_temperature' => 14.0,
                    'racers' => [
                        1 => [
                            'entry_number' => 1,
                            'course_number' => 1,
                            'start_timing_source' => '.15',
                            'start_timing' => 0.15,
                            'weight_source' => '54.0kg',
                            'weight' => 54.0,
                            'weight_adjustment_source' => '0.0',
                            'weight_adjustment' => 0.0,
                            'exhibition_time_source' => '6.86',
                            'exhibition_time' => 6.86,
                            'tilt_adjustment_source' => '-0.5',
                            'tilt_adjustment' => -0.5,
                            'propeller' => null,
                            'parts' => [],
                        ],
                        2 => [
                            'entry_number' => 2,
                            'course_number' => 2,
                            'start_timing_source' => '.22',
                            'start_timing' => 0.22,
                            'weight_source' => '54.2kg',
                            'weight' => 54.2,
                            'weight_adjustment_source' => '0.0',
                            'weight_adjustment' => 0.0,
                            'exhibition_time_source' => '6.89',
                            'exhibition_time' => 6.89,
                            'tilt_adjustment_source' => '-0.5',
                            'tilt_adjustment' => -0.5,
                            'propeller' => null,
                            'parts' => [],
                        ],
                        3 => [
                            'entry_number' => 3,
                            'course_number' => 3,
                            'start_timing_source' => '.19',
                            'start_timing' => 0.19,
                            'weight_source' => '52.6kg',
                            'weight' => 52.6,
                            'weight_adjustment_source' => '0.0',
                            'weight_adjustment' => 0.0,
                            'exhibition_time_source' => '6.88',
                            'exhibition_time' => 6.88,
                            'tilt_adjustment_source' => '-0.5',
                            'tilt_adjustment' => -0.5,
                            'propeller' => null,
                            'parts' => [],
                        ],
                        4 => [
                            'entry_number' => 4,
                            'course_number' => 4,
                            'start_timing_source' => '.18',
                            'start_timing' => 0.18,
                            'weight_source' => '51.2kg',
                            'weight' => 51.2,
                            'weight_adjustment_source' => '0.0',
                            'weight_adjustment' => 0.0,
                            'exhibition_time_source' => '6.80',
                            'exhibition_time' => 6.8,
                            'tilt_adjustment_source' => '-0.5',
                            'tilt_adjustment' => -0.5,
                            'propeller' => null,
                            'parts' => [],
                        ],
                        5 => [
                            'entry_number' => 5,
                            'course_number' => 5,
                            'start_timing_source' => '.05',
                            'start_timing' => 0.05,
                            'weight_source' => '51.6kg',
                            'weight' => 51.6,
                            'weight_adjustment_source' => '0.0',
                            'weight_adjustment' => 0.0,
                            'exhibition_time_source' => '6.81',
                            'exhibition_time' => 6.81,
                            'tilt_adjustment_source' => '-0.5',
                            'tilt_adjustment' => -0.5,
                            'propeller' => null,
                            'parts' => [],
                        ],
                        6 => [
                            'entry_number' => 6,
                            'course_number' => 6,
                            'start_timing_source' => '.11',
                            'start_timing' => 0.11,
                            'weight_source' => '47.5kg',
                            'weight' => 47.5,
                            'weight_adjustment_source' => '0.0',
                            'weight_adjustment' => 0.0,
                            'exhibition_time_source' => '6.76',
                            'exhibition_time' => 6.76,
                            'tilt_adjustment_source' => '-0.5',
                            'tilt_adjustment' => -0.5,
                            'propeller' => null,
                            'parts' => [],
                        ],
                    ],
                ],
            ],
            [
                'arguments' => [Carbon::parse('2019-10-14'), 2, 1],
                'expected' => [
                    'date' => '2019-10-14',
                    'stadium_number' => 2,
                    'race_number' => 1,
                    'weather_as_of_source' => null,
                    'weather_as_of_race_number' => null,
                    'weather_as_of_time' => null,
                    'wind_speed_source' => null,
                    'wind_speed' => null,
                    'wind_direction_number_source' => null,
                    'wind_direction_number' => null,
                    'wave_height_source' => null,
                    'wave_height' => null,
                    'weather_number_source' => null,
                    'weather_number' => null,
                    'air_temperature_source' => null,
                    'air_temperature' => null,
                    'water_temperature_source' => null,
                    'water_temperature' => null,
                    'racers' => array_combine(
                        range(1, 6),
                        array_map(fn(int $entryNumber): array => [
                            'entry_number' => $entryNumber,
                            'course_number' => null,
                            'start_timing_source' => null,
                            'start_timing' => null,
                            'weight_source' => null,
                            'weight' => null,
                            'weight_adjustment_source' => null,
                            'weight_adjustment' => null,
                            'exhibition_time_source' => null,
                            'exhibition_time' => null,
                            'tilt_adjustment_source' => null,
                            'tilt_adjustment' => null,
                            'propeller' => null,
                            'parts' => null,
                        ], range(1, 6)),
                    ),
                ],
            ],
            [
                'arguments' => [Carbon::parse('2026-05-26'), 6, 12],
                'expected' => [
                    'date' => '2026-05-26',
                    'stadium_number' => 6,
                    'race_number' => 12,
                    'weather_as_of_source' => '11R時点',
                    'weather_as_of_race_number' => 11,
                    'weather_as_of_time' => null,
                    'wind_speed_source' => '4m',
                    'wind_speed' => 4,
                    'wind_direction_number_source' => '西',
                    'wind_direction_number' => 13,
                    'wave_height_source' => '2cm',
                    'wave_height' => 2,
                    'weather_number_source' => '晴',
                    'weather_number' => 1,
                    'air_temperature_source' => '23.0℃',
                    'air_temperature' => 23.0,
                    'water_temperature_source' => '24.0℃',
                    'water_temperature' => 24.0,
                    'racers' => [
                        1 => [
                            'entry_number' => 1,
                            'course_number' => 1,
                            'start_timing_source' => '.08',
                            'start_timing' => 0.08,
                            'weight_source' => '52.0kg',
                            'weight' => 52.0,
                            'weight_adjustment_source' => '0.0',
                            'weight_adjustment' => 0.0,
                            'exhibition_time_source' => '6.65',
                            'exhibition_time' => 6.65,
                            'tilt_adjustment_source' => '0.0',
                            'tilt_adjustment' => 0.0,
                            'propeller' => null,
                            'parts' => [],
                        ],
                        2 => [
                            'entry_number' => 2,
                            'course_number' => 2,
                            'start_timing_source' => '.08',
                            'start_timing' => 0.08,
                            'weight_source' => '53.0kg',
                            'weight' => 53.0,
                            'weight_adjustment_source' => '0.0',
                            'weight_adjustment' => 0.0,
                            'exhibition_time_source' => '6.67',
                            'exhibition_time' => 6.67,
                            'tilt_adjustment_source' => '0.0',
                            'tilt_adjustment' => 0.0,
                            'propeller' => null,
                            'parts' => [
                                [
                                    'part_number_source' => 'ピストン',
                                    'part_number' => 1,
                                    'quantity' => 2,
                                ],
                                [
                                    'part_number_source' => 'リング',
                                    'part_number' => 2,
                                    'quantity' => 4,
                                ],
                                [
                                    'part_number_source' => 'シリンダ',
                                    'part_number' => 5,
                                    'quantity' => null,
                                ],
                            ],
                        ],
                        3 => [
                            'entry_number' => 3,
                            'course_number' => 3,
                            'start_timing_source' => '.15',
                            'start_timing' => 0.15,
                            'weight_source' => '53.6kg',
                            'weight' => 53.6,
                            'weight_adjustment_source' => '0.0',
                            'weight_adjustment' => 0.0,
                            'exhibition_time_source' => '6.62',
                            'exhibition_time' => 6.62,
                            'tilt_adjustment_source' => '-0.5',
                            'tilt_adjustment' => -0.5,
                            'propeller' => null,
                            'parts' => [],
                        ],
                        4 => [
                            'entry_number' => 4,
                            'course_number' => 4,
                            'start_timing_source' => '.18',
                            'start_timing' => 0.18,
                            'weight_source' => '52.3kg',
                            'weight' => 52.3,
                            'weight_adjustment_source' => '0.0',
                            'weight_adjustment' => 0.0,
                            'exhibition_time_source' => '6.67',
                            'exhibition_time' => 6.67,
                            'tilt_adjustment_source' => '0.0',
                            'tilt_adjustment' => 0.0,
                            'propeller' => '新',
                            'parts' => [],
                        ],
                        5 => [
                            'entry_number' => 5,
                            'course_number' => 6,
                            'start_timing_source' => '.35',
                            'start_timing' => 0.35,
                            'weight_source' => '52.0kg',
                            'weight' => 52.0,
                            'weight_adjustment_source' => '0.0',
                            'weight_adjustment' => 0.0,
                            'exhibition_time_source' => '6.50',
                            'exhibition_time' => 6.5,
                            'tilt_adjustment_source' => '3.0',
                            'tilt_adjustment' => 3.0,
                            'propeller' => null,
                            'parts' => [],
                        ],
                        6 => [
                            'entry_number' => 6,
                            'course_number' => 5,
                            'start_timing_source' => '.42',
                            'start_timing' => 0.42,
                            'weight_source' => '52.6kg',
                            'weight' => 52.6,
                            'weight_adjustment_source' => '0.0',
                            'weight_adjustment' => 0.0,
                            'exhibition_time_source' => '6.63',
                            'exhibition_time' => 6.63,
                            'tilt_adjustment_source' => '1.5',
                            'tilt_adjustment' => 1.5,
                            'propeller' => null,
                            'parts' => [],
                        ],
                    ],
                ],
            ],
        ];
    }
}
